version: '3'

services:
  testdb-host:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - '3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
