version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: test-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - custom_net

networks:
  custom_net:
    driver: bridge
