version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: test-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - my-custom-net

networks:
  my-custom-net:
    driver: bridge
